# start by pulling the python image
FROM python:3.12.0-alpine
ENV TZ=Europe/Budapest
# copy the requirements file into the image
COPY ./web_server/requirements.txt /app/requirements.txt

WORKDIR /app
# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY ./web_server/server.py /app
ADD ./common/ /common/

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

CMD ["server.py", "./static/" ]
