# pull official base image
FROM node:20.10.0-alpine
# set working directory
WORKDIR /app

# Copies package.json and package-lock.json to Docker environment
COPY ./react_client/package*.json ./

# Installs all node packages
RUN npm install

# Copies everything over to Docker environment
COPY ./react_client .

# Build for production.
RUN npm run build --production

# Install `serve` to run the application.
RUN npm install -g serve

# Run application
#CMD [ "npm", "start" ]
CMD serve -s build