version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    restart: always
    ports:
     - 15672:15672
     - 5672:5672 #remove this
    networks:
      - dog_watch_network

  web_server:
    build: ./web_server
    image: server
    networks:
     - dog_watch_network
    volumes:
     - "/tmp/dog_watch/images/:/app/static"
    restart: always
    ports:
     - 5000:5000
    depends_on:
     - rabbitmq

  camera_service:
    build: ./camera_service
    image: camera_service
    env_file: 
     - ./camera_service/.env
    volumes:
     - "/opt/vc:/opt/vc"
    devices:
     - "/dev/vchiq:/dev/vchiq"
     - "/dev/video0:/dev/video0"
    networks:
     - dog_watch_network
    restart: always
    depends_on:
     - rabbitmq
networks:
  dog_watch_network:

