version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    restart: always
    ports:
     - 15672:15672
     - 5672:5672 #remove this
    networks:
      - dog_watch_network

  web_server:
    build:
      context: ./web_server
      dockerfile: Dockerfile
    image: server
    networks:
     - dog_watch_network
    volumes:
     - "/tmp/dog_watch/images/:/app/static"
    restart: always
    ports:
     - 5000:5000
    depends_on:
     - rabbitmq

  camera_service:
    build:
      context: ./camera_service
      dockerfile: Dockerfile
    image: camera_service
    privileged: true
    group_add:
     - video
    environment:
     - "LD_LIBRARY_PATH: /opt/vc/lib"
    volumes:
     - /opt/vc:/opt/vc
     - /run/udev:/run/udev:ro
     - "/tmp/dog_watch/images/:/images/"
    devices:
     - "/dev/vchiq:/dev/vchiq"
    networks:
     - dog_watch_network
    restart: always
    depends_on:
     - rabbitmq
networks:
  dog_watch_network:

