version: '3.7'
services:
  dog_detector:
    image: dog_detector
    build:
      context: ./
      dockerfile: Dockerfile_dog_detector
    networks:
     - dog_watch_network
    restart: always
    devices:
     - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - "MOTION_DETECTOR_CONTROL_PIN=17"
    depends_on:
     - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    restart: always
    ports:
     - 15672:15672
    networks:
      - dog_watch_network

  web_server:
    build:
      context: ./
      dockerfile: Dockerfile_web_server
    image: server
    networks:
     - dog_watch_network
    volumes:
     - "/tmp/dog_watch/images/:/app/static"
    restart: always
    ports:
     - 5000:5000
    depends_on:
     - rabbitmq

  camera_service:
    build:
      context: ./
      dockerfile: Dockerfile_camera_service
    image: camera_service
    privileged: true
    group_add:
     - video
    environment:
     - "LD_LIBRARY_PATH: /opt/vc/lib"
    volumes:
     - /opt/vc:/opt/vc
     - /run/udev:/run/udev:ro
     - "/tmp/dog_watch/images/:/images/"
    devices:
     - "/dev/vchiq:/dev/vchiq"
    networks:
     - dog_watch_network
    restart: always
    depends_on:
     - rabbitmq
networks:
  dog_watch_network:

